services:
  db:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGPASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      start_period: 5s
      retries: 3
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  uaag:
    image: uaag
    extra_hosts:
      - localhost:host-gateway
    ports:
      - "8080:8080"
    container_name: uaag
    command: ["UserAccountAccessGraph", "rest"]
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
